bundler_args: "--without development"
language: ruby
rvm:
- 2.0.0
- 2.2.0
- 2.3.0
env:
  global:
    secure: R4h1vcshVXcsPmJEAspuY/XBHxyNXbh3jhD7y4VMOZ4MuIgL4Yy+OeMY/+mB74zsbsU/vpcL4gSR72G3so3s/Z/5f8B1CjOlPuIx2W5xlX0O0Duj7dNhWv5MxV2l5lseVEJlN1x+gowfnRJRFWCfzpNSaMRPCrCndQJuWfJyAI27q1HR6kH5Y+AYN6lRssUK1ecNeWlT95COj3l53bgztZr4LPvM0w6B15HR3flJo8B1e/VokLYG3ScjbcZQCU1OItE8mi/CgCkwzIZ7KkBmhsMEPx8to9Ud1ETXwQ+0waGWtbhTxvoRR3ArZsNS4oJfT9hfDTKZIWnQhMXmE9xS+qy2UnW5xF81ng8+bX3/saR0k1LYgVKgWn4NjwUkBw+TD+q1UErqdG2aQbFQqMqsd2+XCbYZW807F/5BxAVPQuQ2h/aMbseO/iFmJctKiCXHO1r4P0X0TkEcYVd3tw34YZM/yczgcXOWSbCKRThjBWCE/zK7S4Rsx0sUn3acRhMCNb26LaLPQctLeGK9UdOf/y5d07SmZ6TSWs9QXVHhBw1RKX1p+n8guZXjuIxQCFsWRGwBlQ14kEovMUrPfsFj2E74C2r3BVXs73PniVe+46e3uvfZYok5tp9PKQgeCm6oH5uROBOw7eCa1UsWYfujzIbMPPFHergjNOev6I34UyE=
